version: "3"

networks: 
  default: 
    driver: bridge
    ipam: 
      config: 
        - subnet: 172.27.0.0/16

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  unbound:
    image: klutchell/unbound
    networks: 
      default:
        ipv4_address: "172.27.0.2"
    ports:
      - '5053:5053/udp'
      - '5053:5053/tcp'
    volumes:
      - './unbound/:/etc/unbound/'
    restart: unless-stopped

    
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks: 
      default:
        ipv4_address: "172.27.0.3"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp"/
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Chicago'
      DNS1: "172.27.0.2#5053"
      DNS2: "172.27.0.2#5053"
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #   - NET_ADMIN
    restart: unless-stopped
